import pygame

BG_COLOR = (0, 0, 0)
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60


PLAYER_WIDTH = 50
PLAYER_HEIGHT = 50
PLAYER_SPEED = 3.5
PLAYER_IMAGE_PATH = "obrazk/R.png"
PLAYER_BULLET_IMG_PATH = "obrazky/bullet.png"
PLAYER_BULET_SPEED =5

ENEMY_IMAGE_PATH = "obrazky/alien{}.png"
ENEMY_SCALE = 0.76
ENEMY_SPEED = 2
ENEMY_DROP = 10
ENEMY_BULLET_IMG_PATH = "obrazky/bullet.png"
ENEMY_BULET_SPEED =4

