import pygame

BG_COLOR = (0, 0, 0)
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60


PLAYER_WIDTH = 50
PLAYER_HEIGHT = 50
PLAYER_SPEED = 3.5
PLAYER_IMAGE_PATH = "obrazk/R.png"
PLAYER_BULLET_IMG_PATH = "obrazky/bullet.png"
PLAYER_BULET_SPEED = 10


ENEMY_IMAGE_PATH = "obrazky/alien{}.png"
ENEMY_SCALE = 0.76
ENEMY_SPEED = 3
ENEMY_DROP = 10
ENEMY_BULLET_IMG_PATH = "obrazky/alien_bullet.png"
ENEMY_BULET_SPEED = 5

ENEMY_HP_BAR_WIDTH = 200
ENEMY_HP_BAR_HEIGHT = 20

EXPLOSION_IMAGE_PATH = "obrazky/exp{}.png"

BOSS_SCALE = 5

WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
YELLOW = (255, 255, 0)
RED = (255, 0, 0)
BLACK = (0, 0, 0)