import pygame

BG_COLOR = (0, 0, 0)
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60


PLAYER_WIDTH = 50
PLAYER_HEIGHT = 50
PLAYER_SPEED = 3.5
PLAYER_IMAGE_PATH = "obrazk/R.png"

ENEMY_IMAGE_PATH = "obrazky/alien{}.png"
ENEMY_SCALE = 1
ENEMY_SPEED = 2
ENEMY_DROP = 10